/**
 * Post-Engagement Harvester — auto-extract learnings on engagement close
 * ─────────────────────────────────────────────────────────────────────
 * When an engagement closes (state='closed', outcome set), this lib
 * captures structured learnings for the knowledge base:
 *   - What was discovered (top facts at handoff vs at close)
 *   - What patterns surfaced
 *   - Which deliverables produced
 *   - Engagement state journey + duration
 *   - Outcome reason (won/lost/no_decision)
 *
 * Output: a Markdown harvest document AND optionally appends to a
 * Cortex /knowledge/learnings/ file. The parent Cortex repo's
 * knowledge-harvester agent can pick this up for further synthesis.
 *
 * Pure deterministic — no LLM. Captures what's in the DB.
 */

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { getEngagement, listArtifacts } from './engagementTracker.mjs';

export function harvestEngagement(db, engagementId, options = {}) {
  const { writeToFolder = null } = options;
  const eng = getEngagement(db, engagementId);
  if (!eng) throw new Error(`Engagement not found: ${engagementId}`);
  if (eng.state !== 'closed') {
    throw new Error(`Engagement not closed yet — state: ${eng.state}. Close before harvesting.`);
  }

  const bank = db.prepare('SELECT * FROM banks WHERE key = ?').get(eng.bank_key);
  const artifacts = listArtifacts(db, { engagementId });
  const handoffSnapshot = eng.handoff_snapshot_json ? JSON.parse(eng.handoff_snapshot_json) : null;

  // Current state of intel (compare against handoff snapshot)
  const factsAtClose = db.prepare(`
    SELECT COUNT(*) c, COUNT(DISTINCT speaker_person_id) s
    FROM meeting_facts WHERE bank_key = ?
  `).get(eng.bank_key);
  const patternsAtClose = db.prepare(`
    SELECT COUNT(*) c FROM pattern_matches WHERE bank_key = ?
  `).get(eng.bank_key);

  // Engagement transitions (derived from emitted Nova signals)
  const transitions = db.prepare(`
    SELECT title, detected_at FROM deal_signals
    WHERE deal_id = ? AND signal_event IN ('engagement_created', 'engagement_transitioned', 'artifact_published')
    ORDER BY detected_at ASC
  `).all(eng.bank_key);

  // Compose harvest document
  const lines = [];
  lines.push(`# Engagement Harvest — ${bank.bank_name}`);
  lines.push('');
  lines.push(`**Engagement**: ${eng.title || eng.engagement_type}`);
  lines.push(`**Type**: ${eng.engagement_type}`);
  lines.push(`**Outcome**: ${eng.outcome || 'unknown'}`);
  lines.push(`**Kickoff**: ${eng.kickoff_date || '—'}`);
  lines.push(`**Closed**: ${eng.closed_at || '—'}`);
  lines.push(`**VC lead**: ${eng.vc_lead || '—'}`);
  lines.push(`**AE lead**: ${eng.ae_lead || '—'}`);
  lines.push('');

  // Duration
  if (eng.kickoff_date && eng.closed_at) {
    const days = Math.floor((new Date(eng.closed_at) - new Date(eng.kickoff_date)) / 86400000);
    lines.push(`**Duration**: ${days} days`);
    lines.push('');
  }

  // Intel growth during engagement
  lines.push('## Intel growth during engagement');
  if (handoffSnapshot) {
    const handoffFacts = handoffSnapshot.meeting_intel?.attributed_fact_count || 0;
    const handoffPatterns = handoffSnapshot.patterns?.total || 0;
    lines.push(`- Attributed facts: ${handoffFacts} (at handoff) → ${factsAtClose.c} (at close)  · Δ +${factsAtClose.c - handoffFacts}`);
    lines.push(`- Corroborated patterns: ${handoffPatterns} (at handoff) → ${patternsAtClose.c} (at close)  · Δ +${patternsAtClose.c - handoffPatterns}`);
  } else {
    lines.push(`- ${factsAtClose.c} attributed facts on file at close`);
    lines.push(`- ${patternsAtClose.c} corroborated patterns at close`);
  }
  lines.push('');

  // Engagement journey
  lines.push('## Engagement journey');
  if (transitions.length === 0) {
    lines.push('_No transitions logged._');
  } else {
    transitions.forEach(t => lines.push(`- ${String(t.detected_at).slice(0, 10)} — ${t.title}`));
  }
  lines.push('');

  // Deliverables produced
  lines.push(`## Deliverables (${artifacts.length})`);
  if (artifacts.length === 0) {
    lines.push('_No deliverables registered._');
  } else {
    artifacts.forEach(a => {
      lines.push(`- **${a.artifact_type}**: ${a.title}${a.published_by ? ` — ${a.published_by}` : ''}`);
      if (a.summary) lines.push(`  - ${a.summary}`);
    });
  }
  lines.push('');

  // Reusable insights — scaffolded for VC follow-up
  lines.push('## Reusable insights (manual annotation suggested)');
  lines.push('- _What worked: …_');
  lines.push('- _What didn\'t: …_');
  lines.push('- _Stakeholder dynamic learned: …_');
  lines.push('- _Pattern reusable on similar banks: …_');
  lines.push('');

  lines.push('---');
  lines.push(`_Harvest generated by Nova post-engagement-harvester on ${new Date().toISOString()}._`);
  const harvestMd = lines.join('\n');

  // Optional write to disk
  let writtenPath = null;
  if (writeToFolder) {
    if (!existsSync(writeToFolder)) mkdirSync(writeToFolder, { recursive: true });
    writtenPath = join(writeToFolder, `${eng.bank_key}_${engagementId.slice(0, 8)}_harvest.md`);
    writeFileSync(writtenPath, harvestMd, 'utf8');
  }

  return {
    engagement_id: engagementId,
    harvest_markdown: harvestMd,
    written_path: writtenPath,
    metrics: {
      duration_days: eng.kickoff_date && eng.closed_at
        ? Math.floor((new Date(eng.closed_at) - new Date(eng.kickoff_date)) / 86400000)
        : null,
      facts_at_close: factsAtClose.c,
      patterns_at_close: patternsAtClose.c,
      artifacts_count: artifacts.length,
      transitions_count: transitions.length,
      outcome: eng.outcome,
    },
  };
}
